name: "Packages UI Tests"

on:
  push:
    branches:
      - main
    paths:
      - "packages/ui/**"
      - .github/actions/setup-node/action.yml
      - .github/workflows/push-tests-packages-ui.yml
      - "!**/README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Unit test, Component Test (Vue2)
        run: npm -w @packages/ui test:2

      - name: Cypress Component Testing (Vue2)
        run: npm -w @packages/ui cy:run:2

      - name: Build (Vue2)
        run: npm -w @packages/ui build:2

      - name: Unit test, Component Test (Vue3)
        run: npm -w @packages/ui test:3

      - name: Cypress Component Testing (Vue3)
        run: npm -w @packages/ui cy:run:3

      - name: Build (Vue3)
        run: npm -w @packages/ui build:3
