name: "Packages UI Tests"

on:
  push:
    branches:
      - main
    paths:
      - "packages/ui/**"
      - .github/actions/setup-node/action.yml
      - .github/workflows/push-tests-packages-ui.yml
      - "!**/README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: (Vue2) Unit test, Component Test
        run: npm -w @packages/ui run test:2

      - name: (Vue2) Cypress Component Testing
        run: npm -w @packages/ui run cy:run:2

      - name: (Vue2) Build
        run: npm -w @packages/ui run build:2

      - name: (Vue3) Unit test, Component Test
        run: npm -w @packages/ui run test:3

      - name: (Vue3) Cypress Component Testing
        run: npm -w @packages/ui run cy:run:3

      - name: (Vue3) Build
        run: npm -w @packages/ui run build:3
